### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by kadyrleev** [cookieyeshq/cookieyes-gtm-template#3]
Followed the instructions to setup Google Consent with CookieYes and GTM but getting 'Uncaught InternalError: too much recursion' error in console and the banner stays when trying to allow GA cookies:
![image](https://user-images.githubusercontent.com/10324311/153962887-7bf017a6-4ea3-4757-bdb1-88e5bc49ef14.png)

The consent banner works fine is the CookieYes tag is disabled in GTM or when GA cookies aren't allowed via Preferences or all cookies rejected.

Please, advise.

**Comment by cookieyeshq** [comment]
Hello @kadyrleev ,

Apologies for the slight delay in responding. We understand your concern and we would be more than happy to help you with the same. 
Since this issue is specific to your case it would be great if you can raise a ticket here: [https://www.cookieyes.com/support/](https://www.cookieyes.com/support/) so that our support team can help you with the same on priority.

**Comment by gweatherson** [comment]
It would be nice rather, to keep this knowledge public. Seeing the same issue. Can you please share the findings and if this issue was resolved?

**Comment by cookieyeshq** [comment]
Hello @gweatherson 

This issue is normally caused by including the Cookieyes Script multiple times in the same page. If you are using this GTM template, please make sure you have removed the manually installed Cookieyes script from the page.

If you are still having trouble figuring out the issue, please send an email to `support@cookieyes.com` so that our support team can help you with the same on priority.
